// Copyright 2024-present Niobium Microsystems, Inc.
// Licensed under the Apache License, Version 2.0.
//
// Plaintext-add example — server side
//
// Loads the CKKS crypto context and the ciphertext generated by client.cpp,
// encodes the plaintext vector [1..10] on the server side, and records the
// EvalAdd(ciphertext, plaintext) operation as a FHETCH instruction trace.
// The trace is then replayed through the FHETCH simulator.
//
// Usage: ./plaintext_add_server [key_dir]

#include "openfhe.h"
#include "niobium/compiler.h"

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;

int main(int argc, char* argv[]) {
    // ---- Niobium compiler setup ----
    niobium::compiler().init(argc, argv);
    niobium::compiler().set_program_info(
        "plaintext_add_server", "1.0",
        "CKKS plaintext+ciphertext add — FHETCH trace recording + replay");
    niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);

    niobium::Compiler::CacheParameters params;
    params.push_back({"workload", "ckks_plaintext_add"});
    niobium::compiler().cache_parameters(params);

    std::string keyDir = "plaintext_add_keys";
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg.find("--") != 0) {
            keyDir = arg;
            break;
        }
    }

    std::cout << "=== CKKS Plaintext-Add — Server ===" << std::endl;
    std::cout << "Loading keys from: " << keyDir << std::endl;

    // ---- Load crypto context ----
    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(keyDir + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("Failed to load crypto context");

    usint ringDim = cc->GetRingDimension();
    std::cout << "Ring dimension: " << ringDim << std::endl;

    // ---- Load input ciphertext ----
    Ciphertext<DCRTPoly> ciph;
    if (!Serial::DeserializeFromFile(keyDir + "/ciphertext.bin", ciph, SerType::BINARY))
        throw std::runtime_error("Failed to load ciphertext");

    // ---- Encode the server-side plaintext [1..10] ----
    // Encoded BEFORE start() so its DCRTPoly tower addresses are stable
    // by the time tag_input captures their coefficient values as live-in.
    std::vector<double> values = {1.0, 2.0, 3.0, 4.0, 5.0,
                                  6.0, 7.0, 8.0, 9.0, 10.0};
    Plaintext pt = cc->MakeCKKSPackedPlaintext(values);

    // ---- Capture crypto context and tag inputs ----
    niobium::compiler().capture_crypto_context(cc);
    niobium::compiler().tag_input("input_cipher", ciph);
    niobium::compiler().tag_input("input_plaintext", pt);

    if (!niobium::compiler().is_cache_valid()) {
        std::cout << "\n--- Recording plaintext-add ---" << std::endl;
        niobium::compiler().start();

        auto ciphertextAfter = cc->EvalAdd(ciph, pt);

        niobium::compiler().probe("output_cipher", ciphertextAfter);
        niobium::compiler().stop();
    }

    // ---- REPLAY: execute trace through the FHETCH simulator ----
    std::cout << "\n--- Replay ---" << std::endl;
    if (!niobium::compiler().replay()) {
        std::cerr << "[ERROR] Replay failed" << std::endl;
        return 1;
    }

    // ---- Extract the simulator's reconstructed probe and serialize ----
    Ciphertext<DCRTPoly> ct_result;
    if (!niobium::compiler().result(cc, "output_cipher", ct_result)) {
        std::cerr << "[ERROR] Could not retrieve output_cipher probe" << std::endl;
        return 1;
    }
    if (!Serial::SerializeToFile(keyDir + "/ct_result.bin", ct_result, SerType::BINARY)) {
        std::cerr << "[ERROR] Failed to serialize result ciphertext" << std::endl;
        return 1;
    }
    std::cout << "Result ciphertext written to " << keyDir << "/ct_result.bin" << std::endl;
    return 0;
}
