// Copyright 2024-present Niobium Microsystems, Inc.
// Licensed under the Apache License, Version 2.0.
//
// Bootstrap example — server side
//
// Loads the CKKS crypto context, keys, and ciphertext generated by client.cpp.
// Records the bootstrapping operation using hollow mode, producing a FHETCH
// instruction trace. Then replays the trace through the FHETCH simulator.
//
// Usage: ./bootstrap_server [key_dir]

#include "openfhe.h"
#include "niobium/compiler.h"

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;

int main(int argc, char* argv[]) {
    // ---- Niobium compiler setup ----
    niobium::compiler().init(argc, argv);
    niobium::compiler().set_program_info(
        "bootstrap_server", "1.0",
        "CKKS bootstrapping — FHETCH trace recording + replay");
    niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);

    niobium::Compiler::CacheParameters params;
    params.push_back({"workload", "ckks_bootstrap"});
    niobium::compiler().cache_parameters(params);

    std::string keyDir = "bootstrap_keys";
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg.find("--") != 0) {
            keyDir = arg;
            break;
        }
    }

    std::cout << "=== CKKS Bootstrap — Server ===" << std::endl;
    std::cout << "Loading keys from: " << keyDir << std::endl;

    // Mirrors the order of the compiler's simple-ckks-bootstrapping.cpp.
    // Address allocation is lazy (compact_address-style), so the loading
    // order no longer matters for the resulting FHETCH id layout — only
    // the order of tag_* calls does. Inputs → keys → precompute gives the
    // same id layout the compiler produces under -O0.

    // ---- Load crypto context ----
    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(keyDir + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("Failed to load crypto context");

    usint ringDim = cc->GetRingDimension();
    std::cout << "Ring dimension: " << ringDim << std::endl;

    // ---- Load keys ----
    std::cout << "Loading eval mult key..." << std::endl;
    {
        std::ifstream mkStream(keyDir + "/mk.bin", std::ios::in | std::ios::binary);
        if (!mkStream.is_open() || !cc->DeserializeEvalMultKey(mkStream, SerType::BINARY))
            throw std::runtime_error("Failed to load eval mult key");
    }

    std::cout << "Loading eval automorphism keys..." << std::endl;
    {
        std::ifstream rkStream(keyDir + "/rk.bin", std::ios::in | std::ios::binary);
        if (!rkStream.is_open() || !cc->DeserializeEvalAutomorphismKey(rkStream, SerType::BINARY))
            throw std::runtime_error("Failed to load eval automorphism keys");
    }

    // ---- Load input ciphertext ----
    Ciphertext<DCRTPoly> ciph;
    if (!Serial::DeserializeFromFile(keyDir + "/ciphertext.bin", ciph, SerType::BINARY))
        throw std::runtime_error("Failed to load ciphertext");

    // ---- Bootstrap precomputation (fires precompute probes) ----
    std::vector<uint32_t> levelBudget = {4, 4};
    cc->EvalBootstrapSetup(levelBudget);

    // ---- Capture crypto context and tag inputs/keys in the order we
    // want them laid out in the FHETCH address space ----
    // capture_crypto_context() also registers the auto-capture hook that
    // walks the CC's bootstrap precompute map at stop() time.
    niobium::compiler().capture_crypto_context(cc);
    niobium::compiler().tag_input("input_cipher", ciph);
    niobium::compiler().tag_keys(cc);

    // Hollow mode skips OpenFHE's real math during recording, which is fast
    // but leaves intermediate polys uninitialized for the simulator.
    // NIOBIUM_BOOTSTRAP_HOLLOW=0 forces real-math recording so every derived
    // poly is populated before the simulator runs.
    bool hollow = true;
    {
        const char* e = std::getenv("NIOBIUM_BOOTSTRAP_HOLLOW");
        if (e && std::string(e) == "0") hollow = false;
    }

    if (!niobium::compiler().is_cache_valid()) {
        std::cout << "\n--- Recording bootstrap (" << (hollow ? "hollow" : "real") << " mode) ---" << std::endl;
        niobium::compiler().enable_hollow_mode(hollow);
        niobium::compiler().start();

        auto ciphertextAfter = cc->EvalBootstrap(ciph);

        niobium::compiler().probe("output_cipher", ciphertextAfter);
        niobium::compiler().stop();
        niobium::compiler().enable_hollow_mode(false);
    }

    // ---- REPLAY: execute trace through the FHETCH simulator ----
    std::cout << "\n--- Replay ---" << std::endl;
    if (!niobium::compiler().replay()) {
        std::cerr << "[ERROR] Replay failed" << std::endl;
        return 1;
    }

    // ---- Extract the simulator's reconstructed probe and serialize ----
    Ciphertext<DCRTPoly> ct_result;
    if (!niobium::compiler().result(cc, "output_cipher", ct_result)) {
        std::cerr << "[ERROR] Could not retrieve output_cipher probe" << std::endl;
        return 1;
    }
    if (!Serial::SerializeToFile(keyDir + "/ct_result.bin", ct_result, SerType::BINARY)) {
        std::cerr << "[ERROR] Failed to serialize result ciphertext" << std::endl;
        return 1;
    }
    std::cout << "Result ciphertext written to " << keyDir << "/ct_result.bin" << std::endl;
    return 0;
}
