name: Update - openfhe Submodule

on:
  schedule:
    # Run at midnight PST (8:00 AM UTC)
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-and-update:
    uses: ./.github/workflows/reusable-submodule-update.yml
    secrets: inherit
    with:
      submodule-path: vendor/openfhe
      submodule-name: openfhe
      submodule-org-repo: NiobiumInc/openfhe-development
      target-branch: nb_main
